/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ChurnRouteImport } from './routes/churn'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as ExpertsExpertIdRouteImport } from './routes/experts.$expertId'
import { Route as ApiProductsRouteImport } from './routes/api.products'
import { Route as ApiEnrollmentsRouteImport } from './routes/api.enrollments'
import { Route as ApiProductsMappingRouteImport } from './routes/api.products.mapping'
import { Route as ApiEnrollmentsUpsertRouteImport } from './routes/api.enrollments.upsert'
import { Route as ApiEnrollmentsUpdateSubscriptionRouteImport } from './routes/api.enrollments.update-subscription'
import { Route as ApiEnrollmentsCheckRouteImport } from './routes/api.enrollments.check'
import { Route as ApiEnrollmentsCancelRouteImport } from './routes/api.enrollments.cancel'
import { Route as ExpertsExpertIdProductsProductIdRouteImport } from './routes/experts.$expertId.products.$productId'
import { Route as ApiEnrollmentsEmailProduct_idRouteImport } from './routes/api.enrollments.$email.$product_id'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurnRoute = ChurnRouteImport.update({
  id: '/churn',
  path: '/churn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRoute,
} as any)
const ExpertsExpertIdRoute = ExpertsExpertIdRouteImport.update({
  id: '/experts/$expertId',
  path: '/experts/$expertId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnrollmentsRoute = ApiEnrollmentsRouteImport.update({
  id: '/api/enrollments',
  path: '/api/enrollments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsMappingRoute = ApiProductsMappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => ApiProductsRoute,
} as any)
const ApiEnrollmentsUpsertRoute = ApiEnrollmentsUpsertRouteImport.update({
  id: '/upsert',
  path: '/upsert',
  getParentRoute: () => ApiEnrollmentsRoute,
} as any)
const ApiEnrollmentsUpdateSubscriptionRoute =
  ApiEnrollmentsUpdateSubscriptionRouteImport.update({
    id: '/update-subscription',
    path: '/update-subscription',
    getParentRoute: () => ApiEnrollmentsRoute,
  } as any)
const ApiEnrollmentsCheckRoute = ApiEnrollmentsCheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => ApiEnrollmentsRoute,
} as any)
const ApiEnrollmentsCancelRoute = ApiEnrollmentsCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => ApiEnrollmentsRoute,
} as any)
const ExpertsExpertIdProductsProductIdRoute =
  ExpertsExpertIdProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => ExpertsExpertIdRoute,
  } as any)
const ApiEnrollmentsEmailProduct_idRoute =
  ApiEnrollmentsEmailProduct_idRouteImport.update({
    id: '/$email/$product_id',
    path: '/$email/$product_id',
    getParentRoute: () => ApiEnrollmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/churn': typeof ChurnRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/api/enrollments': typeof ApiEnrollmentsRouteWithChildren
  '/api/products': typeof ApiProductsRouteWithChildren
  '/experts/$expertId': typeof ExpertsExpertIdRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/students/': typeof StudentsIndexRoute
  '/api/enrollments/cancel': typeof ApiEnrollmentsCancelRoute
  '/api/enrollments/check': typeof ApiEnrollmentsCheckRoute
  '/api/enrollments/update-subscription': typeof ApiEnrollmentsUpdateSubscriptionRoute
  '/api/enrollments/upsert': typeof ApiEnrollmentsUpsertRoute
  '/api/products/mapping': typeof ApiProductsMappingRoute
  '/api/enrollments/$email/$product_id': typeof ApiEnrollmentsEmailProduct_idRoute
  '/experts/$expertId/products/$productId': typeof ExpertsExpertIdProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/churn': typeof ChurnRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/api/enrollments': typeof ApiEnrollmentsRouteWithChildren
  '/api/products': typeof ApiProductsRouteWithChildren
  '/experts/$expertId': typeof ExpertsExpertIdRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/students': typeof StudentsIndexRoute
  '/api/enrollments/cancel': typeof ApiEnrollmentsCancelRoute
  '/api/enrollments/check': typeof ApiEnrollmentsCheckRoute
  '/api/enrollments/update-subscription': typeof ApiEnrollmentsUpdateSubscriptionRoute
  '/api/enrollments/upsert': typeof ApiEnrollmentsUpsertRoute
  '/api/products/mapping': typeof ApiProductsMappingRoute
  '/api/enrollments/$email/$product_id': typeof ApiEnrollmentsEmailProduct_idRoute
  '/experts/$expertId/products/$productId': typeof ExpertsExpertIdProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/churn': typeof ChurnRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/api/enrollments': typeof ApiEnrollmentsRouteWithChildren
  '/api/products': typeof ApiProductsRouteWithChildren
  '/experts/$expertId': typeof ExpertsExpertIdRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/students/': typeof StudentsIndexRoute
  '/api/enrollments/cancel': typeof ApiEnrollmentsCancelRoute
  '/api/enrollments/check': typeof ApiEnrollmentsCheckRoute
  '/api/enrollments/update-subscription': typeof ApiEnrollmentsUpdateSubscriptionRoute
  '/api/enrollments/upsert': typeof ApiEnrollmentsUpsertRoute
  '/api/products/mapping': typeof ApiProductsMappingRoute
  '/api/enrollments/$email/$product_id': typeof ApiEnrollmentsEmailProduct_idRoute
  '/experts/$expertId/products/$productId': typeof ExpertsExpertIdProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/churn'
    | '/import'
    | '/login'
    | '/products'
    | '/api/enrollments'
    | '/api/products'
    | '/experts/$expertId'
    | '/products/$productId'
    | '/students/$id'
    | '/students/'
    | '/api/enrollments/cancel'
    | '/api/enrollments/check'
    | '/api/enrollments/update-subscription'
    | '/api/enrollments/upsert'
    | '/api/products/mapping'
    | '/api/enrollments/$email/$product_id'
    | '/experts/$expertId/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/churn'
    | '/import'
    | '/login'
    | '/products'
    | '/api/enrollments'
    | '/api/products'
    | '/experts/$expertId'
    | '/products/$productId'
    | '/students/$id'
    | '/students'
    | '/api/enrollments/cancel'
    | '/api/enrollments/check'
    | '/api/enrollments/update-subscription'
    | '/api/enrollments/upsert'
    | '/api/products/mapping'
    | '/api/enrollments/$email/$product_id'
    | '/experts/$expertId/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/churn'
    | '/import'
    | '/login'
    | '/products'
    | '/api/enrollments'
    | '/api/products'
    | '/experts/$expertId'
    | '/products/$productId'
    | '/students/$id'
    | '/students/'
    | '/api/enrollments/cancel'
    | '/api/enrollments/check'
    | '/api/enrollments/update-subscription'
    | '/api/enrollments/upsert'
    | '/api/products/mapping'
    | '/api/enrollments/$email/$product_id'
    | '/experts/$expertId/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChurnRoute: typeof ChurnRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ApiEnrollmentsRoute: typeof ApiEnrollmentsRouteWithChildren
  ApiProductsRoute: typeof ApiProductsRouteWithChildren
  ExpertsExpertIdRoute: typeof ExpertsExpertIdRouteWithChildren
  StudentsIdRoute: typeof StudentsIdRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/churn': {
      id: '/churn'
      path: '/churn'
      fullPath: '/churn'
      preLoaderRoute: typeof ChurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/experts/$expertId': {
      id: '/experts/$expertId'
      path: '/experts/$expertId'
      fullPath: '/experts/$expertId'
      preLoaderRoute: typeof ExpertsExpertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enrollments': {
      id: '/api/enrollments'
      path: '/api/enrollments'
      fullPath: '/api/enrollments'
      preLoaderRoute: typeof ApiEnrollmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/mapping': {
      id: '/api/products/mapping'
      path: '/mapping'
      fullPath: '/api/products/mapping'
      preLoaderRoute: typeof ApiProductsMappingRouteImport
      parentRoute: typeof ApiProductsRoute
    }
    '/api/enrollments/upsert': {
      id: '/api/enrollments/upsert'
      path: '/upsert'
      fullPath: '/api/enrollments/upsert'
      preLoaderRoute: typeof ApiEnrollmentsUpsertRouteImport
      parentRoute: typeof ApiEnrollmentsRoute
    }
    '/api/enrollments/update-subscription': {
      id: '/api/enrollments/update-subscription'
      path: '/update-subscription'
      fullPath: '/api/enrollments/update-subscription'
      preLoaderRoute: typeof ApiEnrollmentsUpdateSubscriptionRouteImport
      parentRoute: typeof ApiEnrollmentsRoute
    }
    '/api/enrollments/check': {
      id: '/api/enrollments/check'
      path: '/check'
      fullPath: '/api/enrollments/check'
      preLoaderRoute: typeof ApiEnrollmentsCheckRouteImport
      parentRoute: typeof ApiEnrollmentsRoute
    }
    '/api/enrollments/cancel': {
      id: '/api/enrollments/cancel'
      path: '/cancel'
      fullPath: '/api/enrollments/cancel'
      preLoaderRoute: typeof ApiEnrollmentsCancelRouteImport
      parentRoute: typeof ApiEnrollmentsRoute
    }
    '/experts/$expertId/products/$productId': {
      id: '/experts/$expertId/products/$productId'
      path: '/products/$productId'
      fullPath: '/experts/$expertId/products/$productId'
      preLoaderRoute: typeof ExpertsExpertIdProductsProductIdRouteImport
      parentRoute: typeof ExpertsExpertIdRoute
    }
    '/api/enrollments/$email/$product_id': {
      id: '/api/enrollments/$email/$product_id'
      path: '/$email/$product_id'
      fullPath: '/api/enrollments/$email/$product_id'
      preLoaderRoute: typeof ApiEnrollmentsEmailProduct_idRouteImport
      parentRoute: typeof ApiEnrollmentsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ApiEnrollmentsRouteChildren {
  ApiEnrollmentsCancelRoute: typeof ApiEnrollmentsCancelRoute
  ApiEnrollmentsCheckRoute: typeof ApiEnrollmentsCheckRoute
  ApiEnrollmentsUpdateSubscriptionRoute: typeof ApiEnrollmentsUpdateSubscriptionRoute
  ApiEnrollmentsUpsertRoute: typeof ApiEnrollmentsUpsertRoute
  ApiEnrollmentsEmailProduct_idRoute: typeof ApiEnrollmentsEmailProduct_idRoute
}

const ApiEnrollmentsRouteChildren: ApiEnrollmentsRouteChildren = {
  ApiEnrollmentsCancelRoute: ApiEnrollmentsCancelRoute,
  ApiEnrollmentsCheckRoute: ApiEnrollmentsCheckRoute,
  ApiEnrollmentsUpdateSubscriptionRoute: ApiEnrollmentsUpdateSubscriptionRoute,
  ApiEnrollmentsUpsertRoute: ApiEnrollmentsUpsertRoute,
  ApiEnrollmentsEmailProduct_idRoute: ApiEnrollmentsEmailProduct_idRoute,
}

const ApiEnrollmentsRouteWithChildren = ApiEnrollmentsRoute._addFileChildren(
  ApiEnrollmentsRouteChildren,
)

interface ApiProductsRouteChildren {
  ApiProductsMappingRoute: typeof ApiProductsMappingRoute
}

const ApiProductsRouteChildren: ApiProductsRouteChildren = {
  ApiProductsMappingRoute: ApiProductsMappingRoute,
}

const ApiProductsRouteWithChildren = ApiProductsRoute._addFileChildren(
  ApiProductsRouteChildren,
)

interface ExpertsExpertIdRouteChildren {
  ExpertsExpertIdProductsProductIdRoute: typeof ExpertsExpertIdProductsProductIdRoute
}

const ExpertsExpertIdRouteChildren: ExpertsExpertIdRouteChildren = {
  ExpertsExpertIdProductsProductIdRoute: ExpertsExpertIdProductsProductIdRoute,
}

const ExpertsExpertIdRouteWithChildren = ExpertsExpertIdRoute._addFileChildren(
  ExpertsExpertIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChurnRoute: ChurnRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ApiEnrollmentsRoute: ApiEnrollmentsRouteWithChildren,
  ApiProductsRoute: ApiProductsRouteWithChildren,
  ExpertsExpertIdRoute: ExpertsExpertIdRouteWithChildren,
  StudentsIdRoute: StudentsIdRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
